#!/usr/bin/env python3
"""Generate a combined GSC vs Umami report for a product.

Inputs:
- GSC CSVs (queries + pages) generated by gsc_export_last28d.py
- Umami Cloud API (via UMAMI_API_KEY in /opt/data/.env)

Outputs:
- A markdown report with (1) search demand signals, (2) site behavior, (3) prioritized actions.

Usage:
  source /root/moxie_hq/.venv-moxie/bin/activate
  python3 cmo/scripts/gsc_vs_umami_report.py \
    --product formbeep \
    --umami_site_id 750e37be-3e04-4672-abe8-a2983afb9a4d \
    --gsc_queries /root/moxie/products/formbeep/analytics/inputs/gsc_queries_last28d.csv \
    --gsc_pages /root/moxie/products/formbeep/analytics/inputs/gsc_pages_last28d.csv \
    --out /root/moxie/products/formbeep/analytics/gsc-vs-umami-study.md
"""

from __future__ import annotations

import argparse
import csv
import os
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple
from urllib.parse import urlparse

import requests

UMAMI_BASE = "https://api.umami.is/v1"


def read_env_var_from_file(path: str, key: str) -> str:
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"Missing env file: {path}")
    for line in p.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        if k.strip() == key:
            return v.strip().strip('"').strip("'")
    raise KeyError(f"Missing {key} in {path}")


def load_csv_rows(path: str) -> List[dict]:
    with open(path, newline="", encoding="utf-8") as f:
        r = csv.DictReader(f)
        return list(r)


def as_float(x, default=0.0):
    try:
        return float(x)
    except Exception:
        return default


def as_int(x, default=0):
    try:
        return int(float(x))
    except Exception:
        return default


def norm_path_from_gsc_page(url: str) -> str:
    # GSC page is usually full URL. Normalize to path for matching Umami url metrics.
    try:
        u = urlparse(url)
        return u.path or "/"
    except Exception:
        return url


def umami_get(path: str, api_key: str, timeout=20):
    headers = {"Authorization": f"Bearer {api_key}"}
    resp = requests.get(f"{UMAMI_BASE}{path}", headers=headers, timeout=timeout)
    resp.raise_for_status()
    return resp.json()


def umami_stats(site_id: str, start_at: int, end_at: int, api_key: str) -> dict:
    return umami_get(f"/websites/{site_id}/stats?startAt={start_at}&endAt={end_at}", api_key)


def umami_metrics(site_id: str, start_at: int, end_at: int, type_: str, metric: str, limit: int, api_key: str) -> list:
    return umami_get(
        f"/websites/{site_id}/metrics?startAt={start_at}&endAt={end_at}&type={type_}&metric={metric}&limit={limit}",
        api_key,
    )


def md_table(headers: List[str], rows: List[List[str]]) -> str:
    out = []
    out.append("| " + " | ".join(headers) + " |")
    out.append("|" + "|".join(["---"] * len(headers)) + "|")
    for r in rows:
        out.append("| " + " | ".join(r) + " |")
    return "\n".join(out)


def top_n(rows: List[dict], key_fn, n: int) -> List[dict]:
    return sorted(rows, key=key_fn, reverse=True)[:n]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--product", required=True)
    ap.add_argument("--umami_site_id", required=True)
    ap.add_argument("--gsc_queries", required=True)
    ap.add_argument("--gsc_pages", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--days", type=int, default=28)
    args = ap.parse_args()

    api_key = read_env_var_from_file("/opt/data/.env", "UMAMI_API_KEY")

    # Umami Cloud expects timestamps in MILLISECONDS for this environment.
    # (Seconds returned empty datasets; ms returns real stats.)
    end_at = int(time.time() * 1000)
    start_at = end_at - args.days * 86400 * 1000

    stats = umami_stats(args.umami_site_id, start_at, end_at, api_key)
    top_pages = umami_metrics(args.umami_site_id, start_at, end_at, "url", "pageviews", 50, api_key)
    top_referrers = umami_metrics(args.umami_site_id, start_at, end_at, "referrer", "visitors", 20, api_key)
    top_events = []
    try:
        top_events = umami_metrics(args.umami_site_id, start_at, end_at, "event", "count", 50, api_key)
    except Exception:
        top_events = []

    gq = load_csv_rows(args.gsc_queries)
    gp = load_csv_rows(args.gsc_pages)

    # Normalize + compute derived
    for r in gq:
        r["clicks_i"] = as_int(r.get("clicks"))
        r["impr_i"] = as_int(r.get("impressions"))
        r["ctr_f"] = as_float(r.get("ctr"))
        r["pos_f"] = as_float(r.get("position"))

    for r in gp:
        r["clicks_i"] = as_int(r.get("clicks"))
        r["impr_i"] = as_int(r.get("impressions"))
        r["ctr_f"] = as_float(r.get("ctr"))
        r["pos_f"] = as_float(r.get("position"))
        r["path"] = norm_path_from_gsc_page(r.get("page", ""))

    # Build Umami pageview map
    # Umami returns [{x: '/path', y: pageviews}] for type=url
    umami_pv_by_path: Dict[str, int] = {}
    for r in top_pages:
        p = (r.get("x") or "").strip() or "/"
        umami_pv_by_path[p] = as_int(r.get("y"), 0)

    # Join: add umami pageviews for GSC pages
    for r in gp:
        r["umami_pv"] = umami_pv_by_path.get(r["path"], 0)

    # Opportunity heuristics
    # High impressions, low CTR, mid positions (close to first page)
    opp_pages = [
        r
        for r in gp
        if r["impr_i"] >= 50 and r["ctr_f"] <= 0.01 and 4 <= r["pos_f"] <= 20
    ]
    opp_queries = [
        r
        for r in gq
        if r["impr_i"] >= 50 and r["ctr_f"] <= 0.01 and 4 <= r["pos_f"] <= 20
    ]

    # Report
    lines: List[str] = []
    lines.append(f"# {args.product} — GSC vs Umami (last {args.days}d)")
    lines.append("")
    lines.append("## Executive summary")
    lines.append(f"- Umami: {stats.get('pageviews', 0)} pageviews, {stats.get('visitors', 0)} visitors, {stats.get('visits', 0)} visits (last {args.days}d).")
    lines.append(f"- GSC export rows: queries={len(gq)}, pages={len(gp)} (last {args.days}d export).")
    if not top_events:
        lines.append("- Events: none pulled (either not configured or no data). Conversion diagnosis is limited until we track signup/CTA events.")
    lines.append("")

    lines.append("## Umami — top pages (pageviews)")
    rows = []
    for r in top_pages[:12]:
        rows.append([str(r.get("y", "")), str(r.get("x", ""))])
    lines.append(md_table(["pageviews", "path"], rows) if rows else "(no data)")
    lines.append("")

    lines.append("## Umami — top referrers (visitors)")
    rows = []
    for r in top_referrers[:12]:
        rows.append([str(r.get("y", "")), str(r.get("x", ""))])
    lines.append(md_table(["visitors", "referrer"], rows) if rows else "(no data)")
    lines.append("")

    lines.append("## GSC — top queries (impressions)")
    rows = []
    for r in top_n(gq, lambda x: x["impr_i"], 15):
        rows.append([
            str(r.get("impressions", "")),
            str(r.get("clicks", "")),
            f"{r.get('ctr_f', 0.0)*100:.2f}%",
            f"{r.get('pos_f', 0.0):.1f}",
            (r.get("query") or "")[:80].replace("|", "\\|")
        ])
    lines.append(md_table(["impr", "clicks", "ctr", "pos", "query"], rows) if rows else "(no data)")
    lines.append("")

    lines.append("## GSC — top pages (impressions) + Umami pageviews")
    rows = []
    for r in top_n(gp, lambda x: x["impr_i"], 12):
        rows.append([
            str(r.get("impressions", "")),
            str(r.get("clicks", "")),
            f"{r.get('ctr_f', 0.0)*100:.2f}%",
            f"{r.get('pos_f', 0.0):.1f}",
            str(r.get("umami_pv", 0)),
            (r.get("page") or "")[:60].replace("|", "\\|")
        ])
    lines.append(md_table(["impr", "clicks", "ctr", "pos", "umami_pv", "page"], rows) if rows else "(no data)")
    lines.append("")

    lines.append("## Opportunities (high-impr + low-CTR + position 4–20)")
    if opp_pages:
        rows = []
        for r in top_n(opp_pages, lambda x: x["impr_i"], 12):
            rows.append([
                str(r.get("impressions", "")),
                f"{r.get('ctr_f', 0.0)*100:.2f}%",
                f"{r.get('pos_f', 0.0):.1f}",
                r.get("path", "")
            ])
        lines.append("Pages:")
        lines.append(md_table(["impr", "ctr", "pos", "path"], rows))
        lines.append("")
    else:
        lines.append("Pages: none matched the heuristic (or low GSC volume).")
        lines.append("")

    if opp_queries:
        rows = []
        for r in top_n(opp_queries, lambda x: x["impr_i"], 12):
            rows.append([
                str(r.get("impressions", "")),
                f"{r.get('ctr_f', 0.0)*100:.2f}%",
                f"{r.get('pos_f', 0.0):.1f}",
                (r.get("query") or "")[:80].replace("|", "\\|")
            ])
        lines.append("Queries:")
        lines.append(md_table(["impr", "ctr", "pos", "query"], rows))
        lines.append("")
    else:
        lines.append("Queries: none matched the heuristic (or low GSC volume).")
        lines.append("")

    lines.append("## Prioritized actions (next 7 days)")
    lines.append("P0 (instrumentation):")
    lines.append("- Add Umami events for key CTAs (pricing CTA click, signup start, signup complete). Without events, we can’t separate ‘traffic problem’ from ‘conversion problem’. ")
    lines.append("P0 (search CTR lifts):")
    if opp_pages:
        lines.append("- For the top 1–3 pages in the Opportunities table: rewrite title/meta to match the highest-impression queries; add a short FAQ section targeting those queries.")
    else:
        lines.append("- Low GSC volume: focus on shipping 1–2 SEO pages (WhatsApp + without-Zapier) and internal linking rather than CTR optimizations.")
    lines.append("P1 (content alignment):")
    lines.append("- Compare Umami top pages vs GSC top pages. If a page is high in Umami but absent in GSC, add internal links + ensure it’s in sitemap + has a clear keyword target.")
    lines.append("P2 (ops):")
    lines.append("- Automate this report weekly (cron) now that GSC exporter is working in-container.")
    lines.append("")

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(str(out_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
